#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\Users\asuardi\Desktop\CRANE_Vivado_HLS\final\EDK_FPGA_Hardware\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

SHELL = CMD

XILINX_EDK_DIR = C:/Xilinx/14.6/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

FPGA_ARCH = virtex6

DEVICE = xc6vlx240tff1156-1

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT =  -lp C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf

BRAMINIT_ELF_IMP_FILES = $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_IMP_FILE_ARGS = -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

BRAMINIT_ELF_SIM_FILES = $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_SIM_FILE_ARGS = -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

SIM_CMD = C:\modeltech_10.1c\win32/vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s mgm -X C:/Xilinx/14.4/Modelsim


CORE_STATE_DEVELOPMENT_FILES = C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/netlist/controller_fifo.ngc \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family_support.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/coregen_comp_defs.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/common_types_pkg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/conv_funs_pkg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_pkg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/async_fifo_fg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/sync_fifo_fg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/basic_sfifo_fg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/blk_mem_gen_wrapper.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/addsub.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_bit.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/direct_path_cntr.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/direct_path_cntr_ai.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/down_counter.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/eval_timer.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/inferred_lut4.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_steer.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_steer128.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_mirror128.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ld_arith_reg.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ld_arith_reg2.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/mux_onehot.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_bits.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate128.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_adder_bit.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_adder.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter_bit.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter_top.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_occ_counter.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_occ_counter_top.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_dpram_select.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_mask.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl16_fifo.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo2.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo3.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_rbu.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/valid_be.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_with_enable_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/muxf_struct_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/cntr_incr_decr_addn_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/dynshreg_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/dynshreg_i_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/mux_onehot_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_rbu_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/compare_vectors_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate_f.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/soft_reset.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/axi_lite_ipif_v1_01_a/hdl/vhdl/address_decoder.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/axi_lite_ipif_v1_01_a/hdl/vhdl/slave_attachment.vhd \
C:/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/axi_lite_ipif_v1_01_a/hdl/vhdl/axi_lite_ipif.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/user_logic.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/controller.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/AESL_Comp.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/AESL_Comp_core.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/AESL_pkg.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/controller_dcm.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_FGM_F_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_FGM_premat_xout_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_FGM_premat_xr_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_f_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_10154_ACMP_mul_13.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_10442_ACMP_mul_14.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_10745_ACMP_mul_15.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_11038_ACMP_mul_16.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_11342_ACMP_mul_17.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_11634_ACMP_mul_18.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_11932_ACMP_mul_19.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_12237_ACMP_mul_20.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_12530_ACMP_mul_21.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_12828_ACMP_mul_22.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_13131_ACMP_mul_23.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_13659_ACMP_mul_24.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_13790_ACMP_mul_25.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_14268_ACMP_mul_26.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_14438_ACMP_mul_27.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_15002_ACMP_mul_28.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_15178_ACMP_mul_29.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_15623_ACMP_mul_30.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_15794_ACMP_mul_31.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_16062_ACMP_mul_32.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_16406_ACMP_mul_33.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_16694_ACMP_mul_34.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_17012_ACMP_mul_35.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_17314_ACMP_mul_36.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_17620_ACMP_mul_37.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_17922_ACMP_mul_38.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_18240_ACMP_mul_39.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_18541_ACMP_mul_40.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_18849_ACMP_mul_41.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_19161_ACMP_mul_42.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_20608_ACMP_mul_43.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_21079_ACMP_mul_44.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_7240_ACMP_mul_1.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_7673_ACMP_mul_2.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8073_ACMP_mul_3.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8100_ACMP_mul_4.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8127_ACMP_mul_5.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8238_ACMP_mul_6.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8404_ACMP_mul_7.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8642_ACMP_mul_8.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_8956_ACMP_mul_9.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_9254_ACMP_mul_10.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_9541_ACMP_mul_11.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_grp_fu_9844_ACMP_mul_12.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_premat_xr_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_theta_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_theta_new_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_x_in_int_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_y_int_V.vhd \
C:/Users/asuardi/Desktop/CRANE_Vivado_HLS/final/EDK_Controller/mycores/pcores/controller_v1_00_a/hdl/vhdl/funeval_y_new_V.vhd

WRAPPER_NGC_FILES = implementation/system_proc_sys_reset_0_wrapper.ngc \
implementation/system_microblaze_0_intc_wrapper.ngc \
implementation/system_microblaze_0_ilmb_wrapper.ngc \
implementation/system_microblaze_0_i_bram_ctrl_wrapper.ngc \
implementation/system_microblaze_0_dlmb_wrapper.ngc \
implementation/system_microblaze_0_d_bram_ctrl_wrapper.ngc \
implementation/system_microblaze_0_bram_block_wrapper.ngc \
implementation/system_microblaze_0_wrapper.ngc \
implementation/system_debug_module_wrapper.ngc \
implementation/system_clock_generator_0_wrapper.ngc \
implementation/system_axi_timer_0_wrapper.ngc \
implementation/system_axi4lite_0_wrapper.ngc \
implementation/system_axi4_0_wrapper.ngc \
implementation/system_rs232_uart_1_wrapper.ngc \
implementation/system_ethernet_lite_wrapper.ngc \
implementation/system_ddr3_sdram_wrapper.ngc \
implementation/system_controller_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data\system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK\SDK_Export\hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)
